In [1]:
import pandas as pd
import numpy as np

In [2]:
# wine_x_train.csv - the training set
x_train = pd.read_csv("wine_x_train.csv")  

# prices list for the training set, prices correllates to the wine samples in wine_x_train.csv y row number
y_train = pd.read_csv("wine_y_train.csv")  

In [3]:
print("Size of x_train :",x_train.shape,"\nSize of y_train : ",y_train.shape)

Size of x_train : (65000, 13) 
Size of y_train :  (65000, 2)


In [4]:
y_train.head()

id  price
0   59970   26.0
1  107540   25.0
2   45945   34.0
3   49511   45.0
4   12978   36.0

In [5]:
x_train.head()

id  country                                        description  \
0   59970    Italy  Violet, iris, red berry and spice scents take ...   
1  107540   France  While there is a youthful stalky element to th...   
2   45945  Germany  There are edges of of smoke and violet on this...   
3   49511   Israel  A bouquet of blackberry and juniper sets the s...   
4   12978       US  This has earthy aromas and sun-dried tomato fl...   

                                designation  points      province  \
0                                       NaN      90       Tuscany   
1                                 Tradition      88  Loire Valley   
2  Hochheimer Kirchenstück Spätlese Trocken      90      Rheingau   
3                            Secret Reserve      91  Judean Hills   
4                               Pauli Ranch      84    California   

           region_1 region_2         taster_name taster_twitter_handle  \
0  Chianti Classico      NaN       Kerin O’Keefe          @kerinokeefe   
1     Menetou-Salon      NaN          Roger Voss            @vossroger   
2               NaN      NaN  Anna Lee C. Iijima                   NaN   
3               NaN      NaN       Mike DeSimone        @worldwineguys   
4  Mendocino County      NaN          Jim Gordon      @gordone_cellars   

                                               title             variety  \
0                     Volpaia 2011  Chianti Classico           Red Blend   
1  Isabelle et Pierre Clément 2015 Tradition  (Me...          Pinot Noir   
2  Domdechant Werner 2010 Hochheimer Kirchenstück...            Riesling   
3  Shiloh Winery 2013 Secret Reserve Cabernet Sau...  Cabernet Sauvignon   
4  Muscardini 2010 Pauli Ranch Sangiovese (Mendoc...          Sangiovese   

                       winery  
0                     Volpaia  
1  Isabelle et Pierre Clément  
2           Domdechant Werner  
3               Shiloh Winery  
4                  Muscardini

In [6]:
x_train = x_train.merge(y_train, on = 'id')

In [7]:
x_train.head()

id  country                                        description  \
0   59970    Italy  Violet, iris, red berry and spice scents take ...   
1  107540   France  While there is a youthful stalky element to th...   
2   45945  Germany  There are edges of of smoke and violet on this...   
3   49511   Israel  A bouquet of blackberry and juniper sets the s...   
4   12978       US  This has earthy aromas and sun-dried tomato fl...   

                                designation  points      province  \
0                                       NaN      90       Tuscany   
1                                 Tradition      88  Loire Valley   
2  Hochheimer Kirchenstück Spätlese Trocken      90      Rheingau   
3                            Secret Reserve      91  Judean Hills   
4                               Pauli Ranch      84    California   

           region_1 region_2         taster_name taster_twitter_handle  \
0  Chianti Classico      NaN       Kerin O’Keefe          @kerinokeefe   
1     Menetou-Salon      NaN          Roger Voss            @vossroger   
2               NaN      NaN  Anna Lee C. Iijima                   NaN   
3               NaN      NaN       Mike DeSimone        @worldwineguys   
4  Mendocino County      NaN          Jim Gordon      @gordone_cellars   

                                               title             variety  \
0                     Volpaia 2011  Chianti Classico           Red Blend   
1  Isabelle et Pierre Clément 2015 Tradition  (Me...          Pinot Noir   
2  Domdechant Werner 2010 Hochheimer Kirchenstück...            Riesling   
3  Shiloh Winery 2013 Secret Reserve Cabernet Sau...  Cabernet Sauvignon   
4  Muscardini 2010 Pauli Ranch Sangiovese (Mendoc...          Sangiovese   

                       winery  price  
0                     Volpaia   26.0  
1  Isabelle et Pierre Clément   25.0  
2           Domdechant Werner   34.0  
3               Shiloh Winery   45.0  
4                  Muscardini   36.0

In [8]:
x_train.shape

(65000, 14)

## Cleaning Data

In [9]:
train = x_train[['winery','variety','country','province','price','points']]

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65000 entries, 0 to 64999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   winery    65000 non-null  object 
 1   variety   65000 non-null  object 
 2   country   64965 non-null  object 
 3   province  64965 non-null  object 
 4   price     65000 non-null  float64
 5   points    65000 non-null  int64  
dtypes: float64(1), int64(1), object(4)
memory usage: 3.5+ MB


In [11]:
train['points'].unique()

array([ 90,  88,  91,  84,  85,  86,  89,  87,  83,  82,  92,  80,  93,
        94,  81,  96,  95,  97,  99, 100,  98], dtype=int64)

In [12]:
train['price'].unique()

array([  26.,   25.,   34.,   45.,   36.,   13.,   62.,   10.,   20.,
         33.,   15.,   50.,   24.,   29.,   40.,   19.,    9.,   21.,
         30.,   16.,   46.,   22.,   70.,   41.,   12.,   18.,   14.,
         85.,   32.,   17.,   35.,   38.,   95.,   28.,   11.,   69.,
         75.,   80.,   48.,  110.,   27.,    8.,  212.,   23.,   42.,
         44.,   31.,   37.,  135.,   39.,   60.,   55.,   65.,  130.,
          7.,  195.,   54.,   49.,   90.,   63.,   43.,   72.,   78.,
         68.,   64.,    6.,  140.,  224.,  160.,  100.,  225.,  120.,
        115.,   56.,  328.,   66.,   76.,  117.,  370.,  125.,  639.,
        116.,  200.,  162.,   51.,   58.,  106.,   47.,   57.,  150.,
        105.,   71.,   59.,  231.,  146.,   52.,   96.,   73.,  280.,
        400.,  190.,   86.,   79.,  600.,  260.,   67.,   99.,  450.,
       3300.,   82.,  249.,   89.,  180.,   88.,   53.,  250.,  175.,
        158.,  145., 1125.,  128.,  220.,   83.,   74.,  240.,   98.,
        156.,   81.,

In [13]:
train.isnull().sum()

winery       0
variety      0
country     35
province    35
price        0
points       0
dtype: int64

In [14]:
train.dropna(inplace=True)

C:\Users\91897\AppData\Local\Temp\ipykernel_15044\167719433.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.dropna(inplace=True)


In [15]:
train.isnull().sum()

winery      0
variety     0
country     0
province    0
price       0
points      0
dtype: int64

In [16]:
train.head()

winery             variety  country      province  \
0                     Volpaia           Red Blend    Italy       Tuscany   
1  Isabelle et Pierre Clément          Pinot Noir   France  Loire Valley   
2           Domdechant Werner            Riesling  Germany      Rheingau   
3               Shiloh Winery  Cabernet Sauvignon   Israel  Judean Hills   
4                  Muscardini          Sangiovese       US    California   

   price  points  
0   26.0      90  
1   25.0      88  
2   34.0      90  
3   45.0      91  
4   36.0      84

In [17]:
backup = train.copy()

In [18]:
train = train[train.price.isna() == False]

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64965 entries, 0 to 64999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   winery    64965 non-null  object 
 1   variety   64965 non-null  object 
 2   country   64965 non-null  object 
 3   province  64965 non-null  object 
 4   price     64965 non-null  float64
 5   points    64965 non-null  int64  
dtypes: float64(1), int64(1), object(4)
memory usage: 3.5+ MB


In [20]:
train['winery'] = train['winery'].str.split(' ').str.slice(0,3).str.join(' ')

In [21]:
train['variety'] = train['variety'].str.split(' ').str.slice(0,3).str.join(' ')

In [22]:
train

winery             variety  country        province  price  \
0                 Volpaia           Red Blend    Italy         Tuscany   26.0   
1      Isabelle et Pierre          Pinot Noir   France    Loire Valley   25.0   
2       Domdechant Werner            Riesling  Germany        Rheingau   34.0   
3           Shiloh Winery  Cabernet Sauvignon   Israel    Judean Hills   45.0   
4              Muscardini          Sangiovese       US      California   36.0   
...                   ...                 ...      ...             ...    ...   
64995              Dunham          Chardonnay       US      Washington   24.0   
64996        Eagle Castle          Chardonnay       US      California   18.0   
64997             Bunnell           Red Blend       US      Washington   34.0   
64998          I Capitani           Aglianico    Italy  Southern Italy   17.0   
64999      Fazeli Cellars           Red Blend       US      California   35.0   

       points  
0          90  
1          88  
2          90  
3          91  
4          84  
...       ...  
64995      91  
64996      81  
64997      88  
64998      87  
64999      91  

[64965 rows x 6 columns]

In [23]:
train.to_csv("wine_.csv")

## Cleaned Data

In [24]:
train

winery             variety  country        province  price  \
0                 Volpaia           Red Blend    Italy         Tuscany   26.0   
1      Isabelle et Pierre          Pinot Noir   France    Loire Valley   25.0   
2       Domdechant Werner            Riesling  Germany        Rheingau   34.0   
3           Shiloh Winery  Cabernet Sauvignon   Israel    Judean Hills   45.0   
4              Muscardini          Sangiovese       US      California   36.0   
...                   ...                 ...      ...             ...    ...   
64995              Dunham          Chardonnay       US      Washington   24.0   
64996        Eagle Castle          Chardonnay       US      California   18.0   
64997             Bunnell           Red Blend       US      Washington   34.0   
64998          I Capitani           Aglianico    Italy  Southern Italy   17.0   
64999      Fazeli Cellars           Red Blend       US      California   35.0   

       points  
0          90  
1          88  
2          90  
3          91  
4          84  
...       ...  
64995      91  
64996      81  
64997      88  
64998      87  
64999      91  

[64965 rows x 6 columns]

In [25]:
train = train.reset_index(drop=True)

In [26]:
train.describe()

price        points
count  64965.000000  64965.000000
mean      35.450366     88.427045
std       42.609545      3.042288
min        4.000000     80.000000
25%       17.000000     86.000000
50%       25.000000     88.000000
75%       42.000000     91.000000
max     3300.000000    100.000000

In [27]:
train['price'].max()

3300.0

In [28]:
#Removing Outliers
train = train[train['price']<1000]

In [29]:
train.shape

(64955, 6)

In [30]:
X = train.drop(columns='price')
Y = train['price']

## Applying Train Test Split

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size =0.3)

In [32]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

## Creating an OneHotEncoder object to contain all the possible categories

In [33]:
ohe = OneHotEncoder()
ohe.fit(X[['winery','variety','country','province']])

OneHotEncoder()

## Creating a column transformer to transform categorical columns

In [34]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['winery','variety','country','province']),
                                    remainder='passthrough')

## Linear Regression Model

In [35]:
lr=LinearRegression()

In [36]:
pipe=make_pipeline(column_trans,lr)

In [37]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['1+1=3', '10 Knots', '10Span', ..., 'Ökonomierat Rebholz',
       'àMaurice', 'Štoka'], dtype=object),
                                                                            array(['Abouriou', 'Agiorgitiko', 'Aglianico', 'Airen', 'Albana',
       'Albanello', 'Albariño', 'Albarossa', 'Aleatico', 'Alfrocheiro',...
       'Wairarapa', 'Wairau Valley', 'Walker Bay', 'Washington',
       'Washington-Oregon', 'Weinland Österreich', 'Weinviertel',
       'Wellington', 'Western Australia', 'Western Cape',
       'Wiener Gemischter Satz', 'Württemberg', 'Zenata',
       'Österreichischer Perlwein', 'Österreichischer Sekt', 'Štajerska',
       'Župa'], dtype=object)]),
                                                  ['winery', 'variety',
                                                   'country', 'province'])])),
                ('linearregression', LinearRegression())])

In [38]:
y_pred=pipe.predict(X_test)

In [39]:
y_pred

array([ 9.32149015, 70.04541477, 56.82658728, ..., 51.28920275,
       11.02087936, 36.99411984])

In [40]:
r2_score(y_test,y_pred)

0.4189068591728231

In [41]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Ken Brown','Pinot Noir','US','California',89]).reshape(1,5)))

array([45.42578784])

In [42]:
pipe.steps[0][1].transformers[0][1].categories[0]

array(['1+1=3', '10 Knots', '10Span', ..., 'Ökonomierat Rebholz',
       'àMaurice', 'Štoka'], dtype=object)

In [43]:
import pickle

In [44]:
pickle.dump(pipe,open('Wine_Price_Ml.pkl','wb'))